#!/usr/bin/env python3
"""Regenerate the Rust bindings, addresses, chains, and contracts table.

The bindings, including their mod.rs, come from abi-typegen's `rust` target
(0.8.0 or newer), which emits one alloy `sol!` contract and JSON ABI per
public contract. Addresses, chains,
and the contracts table come from the vendored canonical.json, which is a copy
of ../diesis-js/canonical.json.

    python3 scripts/generate.py          # rewrite everything in place
    python3 scripts/generate.py --check  # fail if anything is out of date

DIESIS_CONTRACTS_DIR overrides the contracts checkout (default
../../diesis-core/diesis/contracts). ABI_TYPEGEN overrides the abi-typegen binary (default
<contracts>/node_modules/.bin/abi-typegen). DIESIS_CANONICAL_JSON overrides the
canonical.json source (default ../diesis-js/canonical.json).
"""

from __future__ import annotations

import argparse
import filecmp
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
GENERATED_REL = Path("src/generated")
CANONICAL_REL = Path("canonical.json")

# Contracts that third-party integrations call. This is the same list as
# diesis-js/scripts/generate-contract-bindings.mjs. The third field names the
# address constant; IValidatorShare has no fixed address, so it gets bindings
# but no contracts table entry.
PUBLIC_CONTRACTS: list[tuple[str, str, str | None]] = [
    ("markets", "IDiesisMarkets", "DIESIS_MARKETS"),
    ("spotBook", "IDiesisSpotBook", "DIESIS_SPOT_BOOK"),
    ("perpsBook", "IDiesisPerpsBook", "DIESIS_PERPS_BOOK"),
    ("margin", "IDiesisMargin", "DIESIS_MARGIN"),
    ("settlement", "IDiesisSettlement", "DIESIS_SETTLEMENT"),
    ("settlementRouter", "DiesisSettlementRouter", "DIESIS_SETTLEMENT_ROUTER"),
    ("conductors", "IDiesisConductors", "DIESIS_CONDUCTORS"),
    ("erc20Factory", "IDiesisErc20Factory", "DIESIS_ERC20_FACTORY"),
    ("perpDeploy", "IDiesisPerpDeploy", "DIESIS_PERP_DEPLOY"),
    ("operatorBond", "IDiesisOperatorBond", "DIESIS_OPERATOR_BOND"),
    ("bundleEscrow", "IDiesisBundleEscrow", "DIESIS_BUNDLE_ESCROW"),
    ("staking", "DiesisStaking", "DIESIS_STAKING"),
    ("position", "IDiesisPosition", "DIESIS_POSITION"),
    ("validatorShare", "IValidatorShare", None),
    ("liquidStakedDS", "ILiquidStakedDS", "LIQUID_STAKED_DS"),
    ("wrappedDS", "IWrappedDS", "WRAPPED_DS"),
    ("patron", "DiesisPatron", "DIESIS_PATRON"),
    ("config", "DiesisConfig", "DIESIS_CONFIG"),
    ("coreVault", "IDiesisCoreVault", "DIESIS_CORE_VAULT"),
    ("issuanceAuction", "IDiesisIssuanceAuction", "DIESIS_ISSUANCE_AUCTION"),
    ("buybackBurn", "IDiesisBuybackBurn", "DIESIS_BUYBACK_BURN"),
    ("shieldedPool", "DiesisShieldedPool", "SHIELDED_POOL"),
    ("privacyPools", "DiesisPrivacyPools", "PRIVACY_POOLS"),
    ("nameRegistry", "IDiesisNameRegistry", "DIESIS_NAME_REGISTRY"),
    ("baseRegistrar", "DiesisBaseRegistrar", "DIESIS_BASE_REGISTRAR"),
    ("publicResolver", "DiesisPublicResolver", "DIESIS_PUBLIC_RESOLVER"),
    ("reverseRegistrar", "IDiesisReverseRegistrar", "DIESIS_REVERSE_REGISTRAR"),
    ("nameVerifier", "IDiesisNameVerifier", "DIESIS_NAME_VERIFIER"),
    ("namePolicy", "IDiesisNamePolicy", "DIESIS_NAME_POLICY"),
]

HEADER = "// Code generated by scripts/generate.py. DO NOT EDIT.\n"
CHAIN_CONSTANTS = {"mainnet": "DIESIS", "testnet": "DIESIS_TESTNET"}


def fail(message: str) -> None:
    print(f"generate.py: {message}", file=sys.stderr)
    sys.exit(1)


def snake_case(name: str) -> str:
    """IDiesisMarkets -> i_diesis_markets, ILiquidStakedDS -> i_liquid_staked_ds."""
    spaced = re.sub(r"(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])", "_", name)
    return spaced.lower()


def screaming_case(key: str) -> str:
    """spotBook -> SPOT_BOOK, liquidStakedDS -> LIQUID_STAKED_DS."""
    return snake_case(key[0].upper() + key[1:]).upper()


def rust_str(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def contracts_dir() -> Path:
    override = os.environ.get("DIESIS_CONTRACTS_DIR")
    return Path(override).resolve() if override else (REPO_ROOT / "../../diesis-core/diesis/contracts").resolve()


def canonical_source() -> Path:
    override = os.environ.get("DIESIS_CANONICAL_JSON")
    return Path(override).resolve() if override else (REPO_ROOT / "../diesis-js/canonical.json").resolve()


MIN_TYPEGEN = (0, 8, 0)


def typegen_path() -> Path:
    override = os.environ.get("ABI_TYPEGEN")
    typegen = Path(override).resolve() if override else contracts_dir() / "node_modules/.bin/abi-typegen"
    if not typegen.exists():
        fail(f"abi-typegen not found at {typegen} (set ABI_TYPEGEN)")
    output = subprocess.run([str(typegen), "--version"], check=True, capture_output=True, text=True).stdout
    match = re.search(r"(\d+)\.(\d+)\.(\d+)", output)
    if not match or tuple(int(part) for part in match.groups()) < MIN_TYPEGEN:
        minimum = ".".join(str(part) for part in MIN_TYPEGEN)
        fail(f"{typegen} reports {output.strip()!r}; abi-typegen {minimum} or newer is required")
    return typegen


def run_typegen(out_dir: Path) -> None:
    """Write abi-typegen's `rust` output, including its mod.rs, into out_dir."""
    typegen = typegen_path()
    artifacts = contracts_dir() / "out"
    if not artifacts.is_dir():
        fail(f"contract artifacts not found at {artifacts} (set DIESIS_CONTRACTS_DIR)")
    names = [contract for _, contract, _ in PUBLIC_CONTRACTS]
    subprocess.run(
        [
            str(typegen),
            "generate",
            "--artifacts",
            str(artifacts),
            "--out",
            str(out_dir),
            "--target",
            "rust",
            "--contracts",
            ",".join(names),
        ],
        check=True,
        stdout=subprocess.DEVNULL,
    )
    produced = sorted(p.name for p in out_dir.iterdir())
    expected = sorted([f"{snake_case(name)}.rs" for name in names] + ["mod.rs"])
    if produced != expected:
        fail(f"abi-typegen produced {produced}, expected {expected}")


def addresses_rs(canonical: dict) -> str:
    entries = canonical["addresses"]
    lines = [
        HEADER,
        "//! System contract and precompile addresses from canonical.json.\n\n",
        "use alloy::primitives::{address, Address};\n\n",
    ]
    for name, value in entries.items():
        lines.append(f"/// `{name}` from canonical.json.\n")
        line = f'pub const {name}: Address = address!("{value}");\n'
        if len(line) > 101:  # rustfmt's max_width is 100 columns
            line = f'pub const {name}: Address =\n    address!("{value}");\n'
        lines.append(line)
    lines.append("\n/// Every address in canonical.json, in file order, keyed by constant name.\n")
    lines.append(f"pub const ALL: [(&str, Address); {len(entries)}] = [\n")
    for name in entries:
        lines.append(f'    ("{name}", {name}),\n')
    lines.append("];\n")
    return "".join(lines)


def chains_rs(canonical: dict) -> str:
    chains = canonical["chains"]
    lines = [
        HEADER,
        "//! Chain definitions from canonical.json.\n\n",
        "use crate::{Chain, NativeCurrency};\n\n",
        "/// `schemaVersion` of the canonical.json these values came from.\n",
        f"pub const SCHEMA_VERSION: u32 = {canonical['schemaVersion']};\n\n",
    ]
    consts = []
    for key, chain in chains.items():
        const = CHAIN_CONSTANTS.get(key, f"DIESIS_{screaming_case(key)}")
        consts.append(const)
        currency = chain["nativeCurrency"]
        lines.extend(
            [
                f"/// {chain['name']} (`{key}` in canonical.json), chain ID {chain['id']}.\n",
                f"pub const {const}: Chain = Chain {{\n",
                f"    key: {rust_str(key)},\n",
                f"    id: {chain['id']},\n",
                f"    name: {rust_str(chain['name'])},\n",
                "    native_currency: NativeCurrency {\n",
                f"        name: {rust_str(currency['name'])},\n",
                f"        symbol: {rust_str(currency['symbol'])},\n",
                f"        decimals: {currency['decimals']},\n",
                "    },\n",
                f"    rpc_url: {rust_str(chain['rpcUrl'])},\n",
                f"    explorer_url: {rust_str(chain['explorerUrl'])},\n",
                f"    testnet: {'true' if chain['testnet'] else 'false'},\n",
                "};\n\n",
            ]
        )
    lines.append("/// Every chain in canonical.json, in file order.\n")
    lines.append(f"pub const ALL: [Chain; {len(consts)}] = [{', '.join(consts)}];\n")
    return "".join(lines)


def contracts_rs(canonical: dict) -> str:
    addresses = canonical["addresses"]
    fixed = [entry for entry in PUBLIC_CONTRACTS if entry[2] is not None]
    lines = [
        HEADER,
        "//! Public system contracts at fixed addresses, keyed like the TypeScript\n",
        "//! SDK's `diesisContracts`.\n\n",
        "use crate::{addresses, bindings, Contract};\n\n",
    ]
    for key, contract, address in fixed:
        if address not in addresses:
            fail(f"{address} for {contract} is missing from canonical.json")
        module = snake_case(contract)
        lines.extend(
            [
                f"/// `{contract}` at [`addresses::{address}`].\n",
                f"pub const {screaming_case(key)}: Contract = Contract {{\n",
                f'    key: "{key}",\n',
                f'    name: "{contract}",\n',
                f"    address: addresses::{address},\n",
                f"    abi: bindings::{module}::{module.upper()}_ABI,\n",
                "};\n\n",
            ]
        )
    lines.append("/// Every public contract with a fixed address, in `diesisContracts` order.\n")
    lines.append(f"pub const ALL: [Contract; {len(fixed)}] = [\n")
    for key, _, _ in fixed:
        lines.append(f"    {screaming_case(key)},\n")
    lines.append("];\n\n")
    lines.append("/// Every public contract that has generated bindings, including those\n")
    lines.append("/// without a fixed address.\n")
    lines.append(f"pub const PUBLIC_CONTRACT_NAMES: [&str; {len(PUBLIC_CONTRACTS)}] = [\n")
    for _, contract, _ in PUBLIC_CONTRACTS:
        lines.append(f'    "{contract}",\n')
    lines.append("];\n")
    return "".join(lines)


def generated_mod() -> str:
    return "".join(
        [
            HEADER,
            "//! Generated code. Run `python3 scripts/generate.py` to rebuild it.\n\n",
            "pub mod addresses;\n",
            "// alloy's `sol(rpc)` expansion gives each contract function an instance\n",
            "// method with one argument per Solidity parameter.\n",
            "#[allow(clippy::too_many_arguments)]\n",
            "pub mod bindings;\n",
            "pub mod chains;\n",
            "pub mod contracts;\n",
        ]
    )


def build(target_root: Path, canonical_path: Path) -> None:
    """Write canonical.json and src/generated/ under target_root."""
    canonical_text = canonical_path.read_text(encoding="utf-8")
    canonical = json.loads(canonical_text)
    (target_root / CANONICAL_REL).write_text(canonical_text, encoding="utf-8")
    generated = target_root / GENERATED_REL
    bindings = generated / "bindings"
    bindings.mkdir(parents=True)
    run_typegen(bindings)
    files = {
        generated / "mod.rs": generated_mod(),
        generated / "addresses.rs": addresses_rs(canonical),
        generated / "chains.rs": chains_rs(canonical),
        generated / "contracts.rs": contracts_rs(canonical),
    }
    for path, text in files.items():
        path.write_text(text, encoding="utf-8")


def tree(root: Path) -> set[Path]:
    return {p.relative_to(root) for p in root.rglob("*") if p.is_file()} if root.exists() else set()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail if generated files are out of date")
    args = parser.parse_args()

    source = canonical_source()
    if not source.exists():
        fail(f"canonical.json not found at {source} (set DIESIS_CANONICAL_JSON)")

    with tempfile.TemporaryDirectory(prefix="diesis-rs-generate-") as tmp:
        fresh = Path(tmp)
        build(fresh, source)
        if args.check:
            stale = []
            if not filecmp.cmp(fresh / CANONICAL_REL, REPO_ROOT / CANONICAL_REL, shallow=False):
                stale.append(str(CANONICAL_REL))
            expected = tree(fresh / GENERATED_REL)
            actual = tree(REPO_ROOT / GENERATED_REL)
            for rel in sorted(expected | actual):
                a, b = fresh / GENERATED_REL / rel, REPO_ROOT / GENERATED_REL / rel
                if rel not in expected or rel not in actual or not filecmp.cmp(a, b, shallow=False):
                    stale.append(str(GENERATED_REL / rel))
            if stale:
                fail("out of date, run `python3 scripts/generate.py`:\n  " + "\n  ".join(stale))
            print("generate.py: up to date")
            return
        shutil.rmtree(REPO_ROOT / GENERATED_REL, ignore_errors=True)
        shutil.copytree(fresh / GENERATED_REL, REPO_ROOT / GENERATED_REL)
        shutil.copyfile(fresh / CANONICAL_REL, REPO_ROOT / CANONICAL_REL)
        print(f"generate.py: wrote {GENERATED_REL} and {CANONICAL_REL}")


if __name__ == "__main__":
    main()
