//! Rust SDK for Diesis.
//!
//! - [`bindings`]: alloy `sol!` bindings for the public system contracts,
//!   generated by abi-typegen, with call and event types, selectors, and an
//!   RPC instance type for each contract.
//! - [`addresses`]: every system contract and precompile address.
//! - [`chains`]: Diesis mainnet and testnet definitions.
//! - [`contracts`]: public contracts at fixed addresses, keyed like the
//!   TypeScript SDK's `diesisContracts`.
//!
//! Addresses and chains come from the vendored `canonical.json`, which the
//! TypeScript and Python SDKs test against too.

#![forbid(unsafe_code)]
#![warn(missing_docs)]

use alloy::primitives::Address;

mod generated;

pub use generated::{addresses, bindings, chains, contracts};

/// The vendored `canonical.json` that addresses and chains are generated from.
pub const CANONICAL_JSON: &str = include_str!("../canonical.json");

/// A Diesis network.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct Chain {
    /// Key in canonical.json, such as `mainnet` or `testnet`.
    pub key: &'static str,
    /// EIP-155 chain ID.
    pub id: u64,
    /// Display name.
    pub name: &'static str,
    /// Native currency.
    pub native_currency: NativeCurrency,
    /// Default public JSON-RPC URL.
    pub rpc_url: &'static str,
    /// Block explorer URL.
    pub explorer_url: &'static str,
    /// Whether this is a test network.
    pub testnet: bool,
}

impl Chain {
    /// Looks up a chain by its chain ID.
    pub fn by_id(id: u64) -> Option<&'static Chain> {
        chains::ALL.iter().find(|chain| chain.id == id)
    }
}

/// A chain's native currency.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NativeCurrency {
    /// Currency name.
    pub name: &'static str,
    /// Ticker symbol.
    pub symbol: &'static str,
    /// Decimal places.
    pub decimals: u8,
}

/// A public system contract at a fixed address.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct Contract {
    /// Key shared with the TypeScript SDK's `diesisContracts`, such as `spotBook`.
    pub key: &'static str,
    /// Solidity contract or interface name, which is also the name of its
    /// generated binding in [`bindings`].
    pub name: &'static str,
    /// Fixed address.
    pub address: Address,
    /// JSON ABI, as generated by abi-typegen.
    pub abi: &'static str,
}

impl Contract {
    /// Looks up a contract by its `diesisContracts` key, such as `staking`.
    pub fn by_key(key: &str) -> Option<&'static Contract> {
        contracts::ALL.iter().find(|contract| contract.key == key)
    }

    /// Looks up a contract by its Solidity name, such as `DiesisStaking`.
    pub fn by_name(name: &str) -> Option<&'static Contract> {
        contracts::ALL.iter().find(|contract| contract.name == name)
    }

    /// Looks up a contract by its address.
    pub fn by_address(address: Address) -> Option<&'static Contract> {
        contracts::ALL
            .iter()
            .find(|contract| contract.address == address)
    }
}

/// Looks up an address by its canonical.json name, such as `DIESIS_STAKING`.
pub fn address(name: &str) -> Option<Address> {
    addresses::ALL
        .iter()
        .find(|(entry, _)| *entry == name)
        .map(|(_, address)| *address)
}

#[cfg(doctest)]
#[doc = include_str!("../README.md")]
pub struct ReadmeDoctests;
